#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x35ecd66e, __VMLINUX_SYMBOL_STR(reset_shadow_zero_bits_mask) },
	{ 0x434693dd, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x7a6bbe36, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0x3555fa29, __VMLINUX_SYMBOL_STR(kvm_mmu_load) },
	{ 0x42ab89c, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0xe4daa863, __VMLINUX_SYMBOL_STR(kvm_require_dr) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x64a34f49, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit_inject) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0x15692c87, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xb1baa6d, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
	{ 0xbacba779, __VMLINUX_SYMBOL_STR(kvm_intr_is_single_vcpu) },
	{ 0x1a5d0dcb, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x65bb06f9, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0xf0215197, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0x45449b56, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x5a03ea9, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0x4c51f664, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_exit) },
	{ 0x4eed1682, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0x5ba08318, __VMLINUX_SYMBOL_STR(kvm_get_rflags) },
	{ 0xdc5f0fb6, __VMLINUX_SYMBOL_STR(ibpb_enabled_key) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0xf8eb5f4b, __VMLINUX_SYMBOL_STR(kvm_vcpu_wake_up) },
	{ 0x7c309fa6, __VMLINUX_SYMBOL_STR(__srcu_read_unlock) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xdf566a59, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r9) },
	{ 0x631ef8ee, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0xc0ef37a2, __VMLINUX_SYMBOL_STR(kvm_cpuid) },
	{ 0x837e790f, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x2620660e, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0x54efb5d6, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x8a26f7b0, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_intercepts) },
	{ 0x97651e6c, __VMLINUX_SYMBOL_STR(vmemmap_base) },
	{ 0x54c7effc, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0xdeb9e564, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_invlpga) },
	{ 0x1d8954a, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0xf9c541d0, __VMLINUX_SYMBOL_STR(speculation_ctrl_update) },
	{ 0x856ad9d6, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xcf5724d2, __VMLINUX_SYMBOL_STR(ssbd_userset_key) },
	{ 0xd92b27a6, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_avic_unaccelerated_access) },
	{ 0xc9f42ce8, __VMLINUX_SYMBOL_STR(kvm_get_cs_db_l_bits) },
	{ 0xfb0eb817, __VMLINUX_SYMBOL_STR(kvm_handle_page_fault) },
	{ 0xc733ff98, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc599bc18, __VMLINUX_SYMBOL_STR(kvm_max_tsc_scaling_ratio) },
	{ 0x7e526bfa, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r10) },
	{ 0xd71e054f, __VMLINUX_SYMBOL_STR(x86_set_memory_region) },
	{ 0xed3be999, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest_page) },
	{ 0x932f9d3e, __VMLINUX_SYMBOL_STR(load_pdptrs) },
	{ 0xa508e36b, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_skinit) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xb8c7ff88, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xd0459e67, __VMLINUX_SYMBOL_STR(kvm_has_tsc_control) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0x5fdfa2c1, __VMLINUX_SYMBOL_STR(amd_pmu_enable_virt) },
	{ 0x3b5dd35e, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_msr) },
	{ 0xf844e95f, __VMLINUX_SYMBOL_STR(spec_ctrl_pcp) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xc801ae6b, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0x479c3c86, __VMLINUX_SYMBOL_STR(find_next_zero_bit) },
	{ 0xbef7acc5, __VMLINUX_SYMBOL_STR(kvm_set_msi_irq) },
	{ 0xfeb92c9d, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0xe974f684, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x7db18851, __VMLINUX_SYMBOL_STR(kvm_is_linear_rip) },
	{ 0x4da72bde, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0x6636c3c9, __VMLINUX_SYMBOL_STR(irq_set_vcpu_affinity) },
	{ 0xb307cc78, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0x19ee3d71, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x59688042, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x6b372259, __VMLINUX_SYMBOL_STR(cpu_present_mask) },
	{ 0xd96a2de6, __VMLINUX_SYMBOL_STR(__srcu_read_lock) },
	{ 0x627e1c63, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0x53a2a3f7, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_inj_virq) },
	{ 0x2e2df7f4, __VMLINUX_SYMBOL_STR(irq_remapping_cap) },
	{ 0x8edde706, __VMLINUX_SYMBOL_STR(retp_enabled_key) },
	{ 0xf2f286c4, __VMLINUX_SYMBOL_STR(kvm_tsc_scaling_ratio_frac_bits) },
	{ 0x7cd8d75e, __VMLINUX_SYMBOL_STR(page_offset_base) },
	{ 0xbe45c43e, __VMLINUX_SYMBOL_STR(kvm_set_rflags) },
	{ 0xab89cae9, __VMLINUX_SYMBOL_STR(kvm_lapic_reg_write) },
	{ 0x7c502ab9, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_intr_vmexit) },
	{ 0xd11b7a3e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xa281370e, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xb601be4c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rdx) },
	{ 0xe96c795, __VMLINUX_SYMBOL_STR(x86_spec_ctrl_base) },
	{ 0x12fa1081, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_pi_irte_update) },
	{ 0x28a1be9b, __VMLINUX_SYMBOL_STR(kvm_vcpu_is_reset_bsp) },
	{ 0xcef3fec5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_write_tsc_offset) },
	{ 0x106b30c8, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x5f6fa8dd, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0xc311ec22, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x155f4108, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xd50e5551, __VMLINUX_SYMBOL_STR(kvm_init_shadow_mmu) },
	{ 0x775a6ef5, __VMLINUX_SYMBOL_STR(kvm_read_and_reset_pf_reason) },
	{ 0x3d9ee9f0, __VMLINUX_SYMBOL_STR(clear_page) },
	{ 0x8918674d, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xbfdcb43a, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r11) },
	{ 0x621820cb, __VMLINUX_SYMBOL_STR(amd_iommu_register_ga_log_notifier) },
	{ 0x910538ff, __VMLINUX_SYMBOL_STR(pv_cpu_ops) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0x1f7af249, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_ple_window) },
	{ 0x130e4bb7, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0x1203c268, __VMLINUX_SYMBOL_STR(kvm_vcpu_gfn_to_page) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0xb261d9d3, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0x232a89c2, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x5df7a209, __VMLINUX_SYMBOL_STR(perf_event_read_value) },
	{ 0xd94cc09, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xcca8dee1, __VMLINUX_SYMBOL_STR(kvm_mtrr_valid) },
	{ 0x954c84eb, __VMLINUX_SYMBOL_STR(reprogram_gp_counter) },
	{ 0xd027fd6a, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0xaf275715, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmrun) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x712fb388, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0xad2a8bd2, __VMLINUX_SYMBOL_STR(x86_bios_cpu_apicid) },
	{ 0x6c4cf4f7, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x1cb4dddf, __VMLINUX_SYMBOL_STR(kvm_spec_ctrl_valid_bits) },
	{ 0x5ccb58f3, __VMLINUX_SYMBOL_STR(smp_ops) },
	{ 0x17e995b1, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0x72392fe6, __VMLINUX_SYMBOL_STR(pv_mmu_ops) },
	{ 0x3f8f9119, __VMLINUX_SYMBOL_STR(kvm_no_apic_vcpu) },
	{ 0x12457dca, __VMLINUX_SYMBOL_STR(x86_spec_ctrl_mask) },
	{ 0xa38f21b9, __VMLINUX_SYMBOL_STR(amd_iommu_update_ga) },
	{ 0x2b865a07, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0x13fd14df, __VMLINUX_SYMBOL_STR(ibrs_present_key) },
	{ 0x7f2c1163, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit) },
	{ 0x487d9343, __VMLINUX_SYMBOL_STR(param_ops_ushort) },
	{ 0x6196b119, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_avic_incomplete_ipi) },
	{ 0xa97eb3a6, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x321fddc7, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0xf858245d, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x18582826, __VMLINUX_SYMBOL_STR(amd_pmu_disable_virt) },
	{ 0xff822689, __VMLINUX_SYMBOL_STR(kvm_apic_match_dest) },
	{ 0x7de3f360, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
	{ 0xd4621642, __VMLINUX_SYMBOL_STR(kvm_arch_has_assigned_device) },
	{ 0x17fbce60, __VMLINUX_SYMBOL_STR(sme_me_mask) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("x86cpu:vendor:*:family:*:model:*:feature:*00C2*");

MODULE_INFO(srcversion, "5F884BE550DDE2F8761E5E0");
MODULE_INFO(rhelversion, "7.9");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
